services:
  bio1server:
    build: 
      context: .
      dockerfile: docker/server.Dockerfile
      args:
        - SERVER_PATH=./bioserv1/bioserver
        - RUN_FILE_PATH=./bioserv1/run_file1.sh
    environment:
      - SERVER_IP=${SERVER_IP}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=biomysql
      - JAVA_DB_PARAMS=${JAVA_DB_PARAMS}
      - DB_DATABASE=${BIO1_DB_DATABASE}
    env_file:
      - .env
    ports:
      - "8300:8300"
      - "8690:8690"
    networks:
      - bio-network

networks:
  bio-network:
    driver: bridge
    name: bio-network
    external: true