services:
  bio2server:
    build: 
      context: .
      dockerfile: docker/server.Dockerfile
      args:
        - SERVER_PATH=./bioserv2/bioserver
        - RUN_FILE_PATH=./bioserv2/run_file2.sh
    environment:
      - SERVER_IP=${SERVER_IP}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${BIO2_DB_DATABASE}
      - DB_HOST=biomysql
      - JAVA_DB_PARAMS=${JAVA_DB_PARAMS}
    env_file:
      - .env
    ports:
      - "8200:8200"
      - "8590:8590"
    networks:
      - bio-network

networks:
  bio-network:
    driver: bridge
    name: bio-network
    external: true